import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/Navber";
import NextProvider from "@/providers/NextProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextProvider>



         <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NavBar></NavBar>
    

        
        {children}
      </body>
      </NextProvider>
     
    </html>
  );
}
